### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by guochunyang** [pythoncn/june#87]
module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/wing/Documents/june/assets/node_modules/nib'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/stylus/bin/stylus:787:10
    at Array.forEach (native)
    at usePlugins (/usr/local/lib/node_modules/stylus/bin/stylus:784:11)
    at /usr/local/lib/node_modules/stylus/bin/stylus:653:9
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
make[1]: *** [stylus] Error 8
make: *** [static] Error 2

之前已经执行了npm install -g stylus component uglify-js nib

我的系统是 mac OS X 10.10.2

**Comment by lepture** [comment]
nib 不能 install -g

**Comment by guochunyang** [comment]
@lepture  已经解决，我去assets目录下，执行了`npm install nib`
